### ISSUE TITLE
Consider a different project name

### ISSUE THREAD

**Issue by aquette** [pluiedev/alien#4]
Alien as a name doesn't help to differentiate from Joey's legacy alien version.

That impacts visibility, but most of all, doesn't ease packaging on distros where alien already exists (trust me, I'm a 19 years Debian Developer Emeritus 😄).

Changing to alien-ng or alien-rust or whatever better would ve wise!

**Comment by pluiedev** [comment]
I was trying to think of a cleverer name but I couldn't :p Any suggestion is welcome

**Comment by aquette** [comment]
Hi @pluiedev 

* alien-ng (my pref 1)
* *alien-pkg* (my other pref 1😄)
* alien-rust

*alien-pkg* seems to be the best though!

**Comment by pluiedev** [comment]
I was thinking of something like *shapeshift* (since that's what it fundamentally does, really, converting between different package formats), but maybe *xenomorph* too as an homage to the original tool :)

**Comment by aquette** [comment]
Great new and refreshing ideas!

Having pkg or package in the name would still be a plus to me, to make it explicit and unique. But I'm sometimes too much an oldschool open source veteran 😅

packageshift or packagemorph (or same with just pkg... pkgshift pkgmorph)

Still, I'm sure Joey loves that alien' mission takes another turn 😉

**Comment by pluiedev** [comment]
I think I'm going with `xenomorph` as it has "morph" in the name and I think indicates what it does much better :D

**Comment by aquette** [comment]
You should only close the ticket when the problem is fully addressed... 😉

**Comment by aquette** [comment]
Still thinking about it: rosetta and package (or pkg)... Even though after the "battle", worth to note
